name: sigma_crm
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  http: ^0.13.4
  flutter_rating_bar: ^4.0.0
  odoo_provider: ^0.0.3
  odoo: ^0.0.2
  odoo_rpc: ^0.5.1
  odoo_repository: ^0.5.2
  mask_text_input_formatter: ^2.1.0
  flutter_typeahead: ^4.0.0
  getwidget: ^3.0.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  percent_indicator: ^4.0.0
  flutter_slidable: ^2.0.0
  flutter_spinkit: ^5.1.0
  intl: ^0.17.0
  # syncfusion_flutter_datepicker: ^20.1.56
  # flutter_tags: ^0.4.9+1
  flutter_native_splash: ^2.2.3+1
  shared_preferences: ^2.0.15
  lottie: ^1.3.0
  smooth_page_indicator: ^1.0.0+2
  # hexcolor: ^2.0.6

flutter_native_splash:
  color: "26408b"
  image: assets/logo-CRM.png

dev_dependencies:
  flutter_test:
    sdk: flutter
    # flutter app icon
  flutter_launcher_icons: #^0.9.3
    git: https://github.com/mthsena/flutter_launcher_icons

#flutter app icon
flutter_icons:
  android: "launcher_icon" #true
  ios: true
  image_path: "assets/logo-CRM.png"
  adaptive_icon_background: "#FFFFFF"

  
  flutter_lints: ^2.0.1


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
